name: Publish
on: push
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Use NodeJS 16'
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
      - name: install lerna globally
        run: npm install --global lerna
      - name: 'Version and publish'
        run: |
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          lerna version
          lerna publish from-git --no-verify-access
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
